export { default as Login } from 'components/Login'
export { default as CourseRegister } from 'components/CourseRegister'
export { default as CofinMap } from 'components/CofinMap'
export { default as Home } from 'components/Home'
export { default as Join } from 'components/Join'
export { default as NavigationForJavaScript } from 'components/NavigationForJavaScript'
export { default as OnlineProfile } from 'components/OnlineProfile'
export { default as SchoolStatus } from 'components/SchoolStatus'